-- AL5AL Gaming Cafe: Customer Credit (آجل) SQL patch for Supabase/PostgreSQL
-- Run once in Supabase SQL Editor.

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  phone varchar(40) not null unique,
  notes text null,
  created_at timestamptz null default now(),
  updated_at timestamptz null default now()
);

alter table public.orders
  add column if not exists customer_id bigint null;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'orders_customer_id_foreign'
  ) THEN
    ALTER TABLE public.orders
      ADD CONSTRAINT orders_customer_id_foreign
      FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
  END IF;
END $$;

create table if not exists public.customer_debts (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  order_id bigint null references public.orders(id) on delete set null,
  device_session_id bigint null references public.device_sessions(id) on delete set null,
  shift_id bigint null references public.shifts(id) on delete set null,
  amount numeric(12,2) not null check (amount >= 0),
  paid_amount numeric(12,2) not null default 0 check (paid_amount >= 0),
  description varchar(255) not null,
  status varchar(20) not null default 'open',
  created_at timestamptz null default now(),
  updated_at timestamptz null default now()
);

create index if not exists customer_debts_customer_status_index
  on public.customer_debts(customer_id, status);

create table if not exists public.customer_debt_payments (
  id bigint generated by default as identity primary key,
  customer_debt_id bigint not null references public.customer_debts(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  payment_method varchar(30) not null default 'cash',
  staff_id bigint null references public.users(id) on delete set null,
  notes text null,
  created_at timestamptz null default now(),
  updated_at timestamptz null default now()
);

-- Laravel API uses the service-role/database connection; these grants also allow
-- authenticated Supabase users to read the tables if Data API access is enabled.
grant select, insert, update, delete on public.customers to authenticated;
grant select, insert, update, delete on public.customer_debts to authenticated;
grant select, insert, update, delete on public.customer_debt_payments to authenticated;
grant usage, select on all sequences in schema public to authenticated;
