-- ==============================================================================
-- AL5AL Gaming & Lounge - Live SQL Patch v2
-- تحديثات الطاولات والخزينة وآجل العملاء لقاعدة بيانات Supabase (PostgreSQL)
-- هذا الملف آمن للتشغيل عدة مرات (Idempotent) ولا يحذف أي بيانات سابقة.
-- ==============================================================================

BEGIN;

-- 1. التأكد من وجود أعمدة وتوقيت الطاولات
ALTER TABLE public.tables 
  ADD COLUMN IF NOT EXISTS occupied_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS current_order_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS total_spent NUMERIC(10,2) NOT NULL DEFAULT 0.00;

-- 2. ربط المدفوعات بالوردية لتتبع النقدية والخزينة بدقة
ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS shift_id BIGINT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payments_shift_id_foreign') THEN
    ALTER TABLE public.payments
      ADD CONSTRAINT payments_shift_id_foreign
      FOREIGN KEY (shift_id) REFERENCES public.shifts(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 3. التأكد من وجود جدول عملاء الآجل
CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(40) NOT NULL UNIQUE,
  notes TEXT NULL,
  created_at TIMESTAMPTZ NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL DEFAULT NOW()
);

-- 4. ربط الطلبات بالعملاء
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS customer_id BIGINT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_customer_id_foreign') THEN
    ALTER TABLE public.orders
      ADD CONSTRAINT orders_customer_id_foreign
      FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 5. جدول ديون العملاء
CREATE TABLE IF NOT EXISTS public.customer_debts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  order_id BIGINT NULL REFERENCES public.orders(id) ON DELETE SET NULL,
  device_session_id BIGINT NULL REFERENCES public.device_sessions(id) ON DELETE SET NULL,
  shift_id BIGINT NULL REFERENCES public.shifts(id) ON DELETE SET NULL,
  amount NUMERIC(12,2) NOT NULL,
  paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  description VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customer_debts_status ON public.customer_debts (customer_id, status);
CREATE INDEX IF NOT EXISTS idx_payments_shift ON public.payments (shift_id, payment_method, status);

COMMIT;

-- تم التحديث بنجاح!
