import React, { useMemo, useState } from 'react';
import { Check, Edit3, Gamepad2, Package, Save, Trash2, UserRound } from 'lucide-react';
import { Device, Product, User } from '../types';
import { Language } from '../i18n/translations';
import { formatMoney } from '../utils/format';
import { api } from '../services/api';

interface Props { lang: Language; products: Product[]; devices: Device[]; user: User | null; onRefresh?: () => Promise<void>; }
type Section = 'products' | 'devices' | 'users';
type ProductDraft = { name: string; name_ar: string; category: Product['category']; price: string; cost_price: string; stock_quantity: string; reorder_level: string };
type DeviceDraft = { room_name: string; room_name_ar: string; device_name: string; device_name_ar: string; device_type: Device['device_type']; hourly_rate: string; specs: string };
type UserDraft = { name: string; email: string; phone: string; pin_code: string; role: User['role']; password: string };

const emptyProduct: ProductDraft = { name: '', name_ar: '', category: 'soft_drinks', price: '', cost_price: '0', stock_quantity: '0', reorder_level: '5' };
const emptyDevice: DeviceDraft = { room_name: '', room_name_ar: '', device_name: '', device_name_ar: '', device_type: 'ps5', hourly_rate: '', specs: '' };
const emptyUser: UserDraft = { name: '', email: '', phone: '', pin_code: '', role: 'staff', password: '' };

export const ManagementDashboard: React.FC<Props> = ({ lang, products: initialProducts, devices: initialDevices, user, onRefresh }) => {
  const ar = lang === 'ar';
  const [section, setSection] = useState<Section>('products');
  const [products, setProducts] = useState<Product[]>(initialProducts);
  const [devices, setDevices] = useState<Device[]>(initialDevices);
  const [users, setUsers] = useState<User[]>(() => JSON.parse(localStorage.getItem('al5al_admin_users') || '[]'));
  const [productDraft, setProductDraft] = useState<ProductDraft>(emptyProduct);
  const [deviceDraft, setDeviceDraft] = useState<DeviceDraft>(emptyDevice);
  const [userDraft, setUserDraft] = useState<UserDraft>(emptyUser);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [notice, setNotice] = useState('');

  const save = <T,>(key: string, value: T) => localStorage.setItem(key, JSON.stringify(value));
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2200); };
  const canManage = user?.role === 'admin' || user?.role === 'manager' || !user;
  const title = useMemo(() => section === 'products' ? (ar ? 'المنتجات والمشروبات' : 'Products & Beverages') : section === 'devices' ? (ar ? 'الألعاب والطاولات' : 'Games & Tables') : (ar ? 'المستخدمون والصلاحيات' : 'Users & Permissions'), [section, ar]);

  if (!canManage) return <div className="p-10 text-center bg-card rounded-2xl border border-border"><UserRound className="mx-auto w-10 h-10 text-rose-400 mb-3" /><p className="font-bold">{ar ? 'ليس لديك صلاحية إدارة البيانات' : 'You do not have management permissions'}</p></div>;

  const reset = () => { setEditingId(null); setProductDraft(emptyProduct); setDeviceDraft(emptyDevice); setUserDraft(emptyUser); };
  const editProduct = (p: Product) => { setEditingId(p.id); setProductDraft({ name: p.name, name_ar: p.name_ar, category: p.category, price: String(p.price), cost_price: String(p.cost_price ?? 0), stock_quantity: String(p.stock_quantity), reorder_level: String(p.reorder_level) }); };
  const submitProduct = async (event: React.FormEvent) => { event.preventDefault(); if (!productDraft.name || !productDraft.name_ar || productDraft.price === '') return;
    const payload = { ...productDraft, price: Number(productDraft.price), cost_price: Number(productDraft.cost_price || 0), stock_quantity: Number(productDraft.stock_quantity), reorder_level: Number(productDraft.reorder_level) };
    const response = editingId ? await api.updateProduct(editingId, payload) : await api.createProduct(payload);
    setProducts(prev => editingId ? prev.map(p => p.id === editingId ? response.product : p) : [...prev, response.product]); await onRefresh?.(); reset(); flash(ar ? 'تم حفظ المنتج في قاعدة البيانات' : 'Product saved to database');
  };
  const removeProduct = (id: number) => { if (!confirm(ar ? 'حذف المنتج؟' : 'Delete this product?')) return; setProducts(prev => prev.filter(p => p.id !== id)); };
  const editDevice = (d: Device) => { setEditingId(d.id); setDeviceDraft({ room_name: d.room_name, room_name_ar: d.room_name_ar || '', device_name: d.device_name, device_name_ar: d.device_name_ar || '', device_type: d.device_type, hourly_rate: String(d.hourly_rate), specs: d.specs || '' }); };
  const submitDevice = async (event: React.FormEvent) => { event.preventDefault(); if (!deviceDraft.room_name || !deviceDraft.device_name || deviceDraft.hourly_rate === '') return;
    const payload = { ...deviceDraft, hourly_rate: Number(deviceDraft.hourly_rate) };
    const response = editingId ? await api.updateDevice(editingId, payload) : await api.createDevice(payload);
    setDevices(prev => editingId ? prev.map(d => d.id === editingId ? response.device : d) : [...prev, response.device]); await onRefresh?.(); reset(); flash(ar ? 'تم حفظ اللعبة/الطاولة في قاعدة البيانات' : 'Game/table saved to database');
  };
  const removeDevice = async (id: number) => { if (!confirm(ar ? 'حذف اللعبة/الطاولة؟' : 'Delete this game/table?')) return; await api.deleteDevice(id); setDevices(prev => prev.filter(d => d.id !== id)); };
  const submitUser = (event: React.FormEvent) => { event.preventDefault(); if (!userDraft.name || !userDraft.email || (!editingId && !userDraft.password)) return;
    const item: User = { id: editingId || Date.now(), name: userDraft.name, email: userDraft.email, phone: userDraft.phone, pin_code: userDraft.pin_code, role: userDraft.role };
    const next = editingId ? users.map(u => u.id === editingId ? { ...u, ...item } : u) : [...users, item]; setUsers(next); save('al5al_admin_users', next); reset(); flash(ar ? 'تم حفظ المستخدم' : 'User saved');
  };
  const removeUser = (id: number) => { if (!confirm(ar ? 'حذف المستخدم؟' : 'Delete this user?')) return; const next = users.filter(u => u.id !== id); setUsers(next); save('al5al_admin_users', next); };
  const input = 'w-full rounded-xl bg-surface border border-border px-3 py-2.5 text-sm outline-none focus:border-primary';
  const tabs = [{ id: 'products' as Section, label: ar ? 'منتجات ومشروبات' : 'Products', icon: Package }, { id: 'devices' as Section, label: ar ? 'ألعاب وطاولات' : 'Games & Tables', icon: Gamepad2 }, { id: 'users' as Section, label: ar ? 'مستخدمين' : 'Users', icon: UserRound }];

  return <div className="space-y-5">
    <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 bg-surface/60 border border-border p-5 rounded-2xl"><div><h2 className="text-xl font-black text-white">{ar ? 'لوحة التحكم' : 'Management Dashboard'}</h2><p className="text-xs text-slate-400 mt-1">{ar ? 'إضافة وتعديل وحذف بيانات الصالة' : 'Add, edit and remove cafe operations data'}</p></div><div className="flex gap-2 flex-wrap">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setSection(id); reset(); }} className={`flex items-center gap-2 px-3 py-2 rounded-xl text-xs font-bold border transition ${section === id ? 'bg-primary text-white border-primary' : 'bg-card text-slate-300 border-border'}`}><Icon className="w-4 h-4" />{label}</button>)}</div></div>
    {notice && <div className="p-3 rounded-xl bg-emerald-500/15 border border-emerald-500/40 text-emerald-300 text-sm flex items-center gap-2"><Check className="w-4 h-4" />{notice}</div>}
    {section === 'products' && <><div className="flex flex-wrap gap-3 text-[11px] text-slate-400"><span>سعر البيع = السعر للعميل</span><span>سعر التكلفة = تكلفة شراء المنتج (يمكن أن تكون 0)</span><span>الكمية = عدد الوحدات في المخزون</span></div><form onSubmit={submitProduct} className="grid grid-cols-2 md:grid-cols-7 gap-3 bg-card border border-border p-4 rounded-2xl"><input className={input} placeholder={ar ? 'اسم المنتج' : 'Product name'} value={productDraft.name} onChange={e => setProductDraft({ ...productDraft, name: e.target.value })} /><input className={input} placeholder={ar ? 'الاسم بالعربي' : 'Arabic name'} value={productDraft.name_ar} onChange={e => setProductDraft({ ...productDraft, name_ar: e.target.value })} /><select className={input} value={productDraft.category} onChange={e => setProductDraft({ ...productDraft, category: e.target.value as Product['category'] })}><option value="hot_drinks">Hot drinks</option><option value="cold_drinks">Cold drinks</option><option value="soft_drinks">Soft drinks</option><option value="snacks">Snacks</option><option value="food">Food</option></select><input className={input} type="number" min="0" title="سعر البيع / Sale price" placeholder={ar ? 'سعر البيع' : 'Sale price'} value={productDraft.price} onChange={e => setProductDraft({ ...productDraft, price: e.target.value })} /><input className={input} type="number" min="0" title="سعر التكلفة / Cost price" placeholder={ar ? 'سعر التكلفة' : 'Cost price'} value={productDraft.cost_price} onChange={e => setProductDraft({ ...productDraft, cost_price: e.target.value })} /><input className={input} type="number" min="0" title="الكمية / Stock quantity" placeholder={ar ? 'الكمية في المخزون' : 'Stock quantity'} value={productDraft.stock_quantity} onChange={e => setProductDraft({ ...productDraft, stock_quantity: e.target.value })} /><button className="rounded-xl bg-primary text-white font-bold text-sm flex items-center justify-center gap-2"><Save className="w-4 h-4" />{editingId ? (ar ? 'تعديل' : 'Update') : (ar ? 'إضافة' : 'Add')}</button></form><List title={title} count={products.length}>{products.map(p => <Row key={p.id} title={ar ? p.name_ar : p.name} sub={`${p.category} • cost ${formatMoney(p.cost_price)} • ${p.stock_quantity} units`} value={`${formatMoney(p.price)} EGP`} onEdit={() => editProduct(p)} onDelete={() => removeProduct(p.id)} />)}</List></>}
    {section === 'devices' && <><form onSubmit={submitDevice} className="grid grid-cols-2 md:grid-cols-7 gap-3 bg-card border border-border p-4 rounded-2xl"><input className={input} placeholder={ar ? 'الغرفة' : 'Room'} value={deviceDraft.room_name} onChange={e => setDeviceDraft({ ...deviceDraft, room_name: e.target.value })} /><input className={input} placeholder={ar ? 'اسم اللعبة/الطاولة' : 'Game/table name'} value={deviceDraft.device_name} onChange={e => setDeviceDraft({ ...deviceDraft, device_name: e.target.value })} /><select className={input} value={deviceDraft.device_type} onChange={e => setDeviceDraft({ ...deviceDraft, device_type: e.target.value as Device['device_type'] })}><option value="ps5">PS5</option><option value="ps4">PS4</option><option value="billiards">Billiards</option><option value="pingpong">Ping Pong</option><option value="pc">PC</option><option value="other">Other</option></select><input className={input} type="number" min="0" placeholder={ar ? 'سعر الساعة' : 'Hourly price'} value={deviceDraft.hourly_rate} onChange={e => setDeviceDraft({ ...deviceDraft, hourly_rate: e.target.value })} /><input className={`${input} md:col-span-2`} placeholder={ar ? 'المواصفات' : 'Specs'} value={deviceDraft.specs} onChange={e => setDeviceDraft({ ...deviceDraft, specs: e.target.value })} /><button className="rounded-xl bg-primary text-white font-bold text-sm flex items-center justify-center gap-2"><Save className="w-4 h-4" />{editingId ? (ar ? 'تعديل' : 'Update') : (ar ? 'إضافة' : 'Add')}</button></form><List title={title} count={devices.length}>{devices.map(d => <Row key={d.id} title={ar ? d.device_name_ar || d.device_name : d.device_name} sub={`${d.room_name} • ${d.device_type}`} value={`${formatMoney(d.hourly_rate)} EGP/hr`} onEdit={() => editDevice(d)} onDelete={() => removeDevice(d.id)} />)}</List></>}
    {section === 'users' && <><form onSubmit={submitUser} className="grid grid-cols-2 md:grid-cols-7 gap-3 bg-card border border-border p-4 rounded-2xl"><input className={input} placeholder={ar ? 'الاسم' : 'Full name'} value={userDraft.name} onChange={e => setUserDraft({ ...userDraft, name: e.target.value })} /><input className={input} type="email" placeholder="Email" value={userDraft.email} onChange={e => setUserDraft({ ...userDraft, email: e.target.value })} /><input className={input} placeholder={ar ? 'الهاتف' : 'Phone'} value={userDraft.phone} onChange={e => setUserDraft({ ...userDraft, phone: e.target.value })} /><input className={input} placeholder="PIN" value={userDraft.pin_code} onChange={e => setUserDraft({ ...userDraft, pin_code: e.target.value })} /><select className={input} value={userDraft.role} onChange={e => setUserDraft({ ...userDraft, role: e.target.value as User['role'] })}><option value="staff">Staff</option><option value="manager">Manager</option><option value="admin">Admin</option></select><input className={input} type="password" placeholder={ar ? 'كلمة المرور' : 'Password'} value={userDraft.password} onChange={e => setUserDraft({ ...userDraft, password: e.target.value })} /><button className="rounded-xl bg-primary text-white font-bold text-sm flex items-center justify-center gap-2"><Save className="w-4 h-4" />{editingId ? (ar ? 'تعديل' : 'Update') : (ar ? 'إضافة' : 'Add')}</button></form><List title={title} count={users.length}>{users.map(u => <Row key={u.id} title={u.name} sub={`${u.email} • ${u.role}`} value={u.phone || ''} onEdit={() => { setEditingId(u.id); setUserDraft({ name: u.name, email: u.email, phone: u.phone || '', pin_code: u.pin_code || '', role: u.role, password: '' }); }} onDelete={() => removeUser(u.id)} />)}</List></>}
  </div>;
};

const List: React.FC<{ title: string; count: number; children: React.ReactNode }> = ({ title, count, children }) => <div className="bg-card border border-border rounded-2xl overflow-hidden"><div className="flex items-center justify-between p-4 border-b border-border"><h3 className="font-bold text-white">{title}</h3><span className="text-xs text-slate-400">{count} items</span></div><div className="divide-y divide-border/60">{children}</div></div>;
const Row: React.FC<{ title: string; sub: string; value: string; onEdit: () => void; onDelete: () => void }> = ({ title, sub, value, onEdit, onDelete }) => <div className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="font-bold text-sm text-white truncate">{title}</p><p className="text-xs text-slate-400 truncate">{sub}</p></div><div className="flex items-center gap-2"><span className="text-sm font-mono text-amber-400 whitespace-nowrap">{value}</span><button onClick={onEdit} className="p-2 rounded-lg bg-surface text-cyan-400 hover:text-white" title="Edit"><Edit3 className="w-4 h-4" /></button><button onClick={onDelete} className="p-2 rounded-lg bg-surface text-rose-400 hover:text-white" title="Delete"><Trash2 className="w-4 h-4" /></button></div></div>;
