-- نظام أجل العملاء / Customer credit ledger
-- Run once in Supabase SQL Editor. Safe to run again.

CREATE TABLE IF NOT EXISTS public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  phone varchar(40) NOT NULL UNIQUE,
  notes text NULL,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now()
);

ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS is_archived boolean NOT NULL DEFAULT false;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS customer_id bigint NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_customer_id_foreign') THEN
    ALTER TABLE public.orders
      ADD CONSTRAINT orders_customer_id_foreign
      FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.customer_debts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  order_id bigint NULL REFERENCES public.orders(id) ON DELETE SET NULL,
  device_session_id bigint NULL REFERENCES public.device_sessions(id) ON DELETE SET NULL,
  shift_id bigint NULL REFERENCES public.shifts(id) ON DELETE SET NULL,
  amount numeric(12,2) NOT NULL,
  paid_amount numeric(12,2) NOT NULL DEFAULT 0,
  description varchar(255) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'open',
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS customer_debts_customer_status_index
  ON public.customer_debts (customer_id, status);

CREATE TABLE IF NOT EXISTS public.customer_debt_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_debt_id bigint NOT NULL REFERENCES public.customer_debts(id) ON DELETE CASCADE,
  amount numeric(12,2) NOT NULL,
  payment_method varchar(30) NOT NULL DEFAULT 'cash',
  staff_id bigint NULL REFERENCES public.users(id) ON DELETE SET NULL,
  notes text NULL,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS customer_debt_payments_debt_index
  ON public.customer_debt_payments (customer_debt_id);

-- تحصيل الدين يدخل في الشيفت الحالي والخزنة الحالية.
ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS shift_id bigint NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payments_shift_id_foreign') THEN
    ALTER TABLE public.payments
      ADD CONSTRAINT payments_shift_id_foreign
      FOREIGN KEY (shift_id) REFERENCES public.shifts(id) ON DELETE SET NULL;
  END IF;
END $$;

-- Optional: keep updated_at current when records change.
CREATE OR REPLACE FUNCTION public.set_customer_credit_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS customers_set_updated_at ON public.customers;
CREATE TRIGGER customers_set_updated_at BEFORE UPDATE ON public.customers
FOR EACH ROW EXECUTE FUNCTION public.set_customer_credit_updated_at();

DROP TRIGGER IF EXISTS customer_debts_set_updated_at ON public.customer_debts;
CREATE TRIGGER customer_debts_set_updated_at BEFORE UPDATE ON public.customer_debts
FOR EACH ROW EXECUTE FUNCTION public.set_customer_credit_updated_at();

DROP TRIGGER IF EXISTS customer_debt_payments_set_updated_at ON public.customer_debt_payments;
CREATE TRIGGER customer_debt_payments_set_updated_at BEFORE UPDATE ON public.customer_debt_payments
FOR EACH ROW EXECUTE FUNCTION public.set_customer_credit_updated_at();

-- Verify after running:
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public'
-- AND table_name IN ('customers','customer_debts','customer_debt_payments');
